01-Builiding Blocks

diff --git a/.github/workflows/01.Building_blocks.yaml b/.github/workflows/01.Building_blocks.yaml
--- a/.github/workflows/01.Building_blocks.yaml
+++ b/.github/workflows/01.Building_blocks.yaml
@@ -1,1 +1,20 @@
+name: 01 - Building Blocks
+on: push 
+
+jobs:
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Say Hello
+        run: echo "Helloe World!"
+  
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+        - name: Failed Step
+          run: |
+           echo "This wll Fail"
+           exit 1
+        - name: Say goodby
+          run: echo "Good Bye!"
 
